spring:
  jpa:
    hibernate.ddl-auto: "validate"
  datasource:
    url: "jdbc:mysql://localhost/test"
    username: "dbuser"
    password: "dbpass"
server:
  error:
    whitelabel:
      enabled: false