spring:
  jpa:
    hibernate.ddl-auto: "create-drop"
  datasource:
    embedded-database-connection: h2
    url: "jdbc:mysql://localhost/test"
    username: "dbuser"
    password: "dbpass"
  security:
    enabled: false
security:
  basic:
    enabled: false
managment:
  security:
    enabled: false
