spring:
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: "none"
    show-sql: false
    database-platform: ${DATABASE_PLATFORM:org.hibernate.dialect.MySQLDialect}
  datasource:
    url: ${DATABASE_URL}
    driverClassName: ${DATABASE_DRIVER_CLASSNAME:com.mysql.jdbc.Driver}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
management:
  health:
    defaults:
      enabled: true
    db:
      enabled: true
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  defaults:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health
      discovery:
        enabled: true
  endpoint:
    startup:
      access: unrestricted
    health:
      probes:
        enabled: true
logging:
  level:
    root: warn
server:
  error:
    whitelabel:
      enabled: false