package ch.denic0la.konfi.brunch.data;

import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.*;
import java.util.stream.Collectors;

import org.modelmapper.ModelMapper;
import org.openapitools.jackson.nullable.JsonNullable;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import ch.denic0la.openapi.konfi.brunch.model.BrunchCreateDTO;
import ch.denic0la.openapi.konfi.brunch.model.BrunchInfoDTO;
import ch.denic0la.openapi.konfi.brunch.model.BrunchQuestionDTO;
import ch.denic0la.openapi.konfi.brunch.model.BrunchQuestionInfoDTO;
import lombok.extern.java.Log;

@Service("brunchService")
@Log
public class BrunchService {

  @Autowired private ModelMapper modelMapper;

  public BrunchInfoDTO brunchToBrunchInfoDTO(Brunch brunch) {
    BrunchInfoDTO dto = new BrunchInfoDTO();

    dto.setId(brunch.getId());
    dto.setTitle(brunch.getTitle());
    dto.setRequireEmail(brunch.getRequireEmail());

    // Use JsonNullable wrappers
    dto.setEmailRegexp(JsonNullable.of(brunch.getEmailRegexp()));

    // Convert List<Question> to Set<BrunchQuestionInfoDTO>
    Set<BrunchQuestionInfoDTO> questionDTOs =
        brunch.getQuestions().stream()
            .map(this::questionToBrunchQuestionInfoDTO)
            .collect(Collectors.toCollection(LinkedHashSet::new));
    dto.setQuestions(questionDTOs);

    return dto;
  }

  public BrunchQuestionInfoDTO questionToBrunchQuestionInfoDTO(Question question) {
    BrunchQuestionInfoDTO dto = new BrunchQuestionInfoDTO();

    dto.setId(question.getId());

    dto.setMin(question.getMin() != null ? question.getMin() : 1);
    dto.setMax(question.getMax() != null ? question.getMax() : 5);

    dto.setTitle(JsonNullable.of(question.getTitle()));
    dto.setOptional(Boolean.TRUE.equals(question.getOptional()));

    if (question.getLink() != null) {
      try {
        dto.setLink(JsonNullable.of(question.getLink().toURI()));
      } catch (URISyntaxException e) {
        log.warning(
            "Failed to convert URL to URI for question "
                + question.getId()
                + ": "
                + question.getLink()
                + ". Error: "
                + e.getMessage());
        dto.setLink(JsonNullable.undefined());
      }
    } else {
      dto.setLink(JsonNullable.undefined());
    }

    dto.setOrder(question.getOrder());
    dto.setRecommended(question.getRecommended());

    return dto;
  }

  private URL uriToUrl(URI uri) {
    if (uri == null) {
      return null;
    }
    try {
      return uri.toURL();
    } catch (MalformedURLException e) {
      log.warning("Failed to convert URI to URL: " + uri + ". Error: " + e.getMessage());
      return null;
    } catch (IllegalArgumentException e) {
      log.warning("Invalid URI format: " + uri + ". Error: " + e.getMessage());
      return null;
    }
  }

  private Question mapToQuestionEntity(BrunchQuestionDTO dto, Brunch brunch) {
    Question question = new Question();

    // ID is auto-generated by JPA, don't set it manually

    question.setTitle(
        dto.getTitle() != null && dto.getTitle().isPresent() ? dto.getTitle().get() : null);
    question.setLink(
        dto.getLink() != null && dto.getLink().isPresent() ? uriToUrl(dto.getLink().get()) : null);
    question.setMin(dto.getMin() != null ? dto.getMin() : 1);
    question.setMax(dto.getMax() != null ? dto.getMax() : 5);
    question.setOptional(Boolean.TRUE.equals(dto.getOptional()));

    question.setOrder(
        dto.getOrder() != null && dto.getOrder().isPresent() ? dto.getOrder().get() : null);
    question.setRecommended(
        dto.getRecommended() != null && dto.getRecommended().isPresent()
            ? dto.getRecommended().get()
            : null);

    question.setBrunch(brunch); // Set owning side

    return question;
  }

  public Brunch brunchCreateDTOToBrunch(BrunchCreateDTO brunchCreate) {
    Brunch brunch = new Brunch();

    brunch.setId(brunchCreate.getId());
    brunch.setTitle(brunchCreate.getTitle());
    brunch.setRequireEmail(
        brunchCreate.getRequireEmail() != null ? brunchCreate.getRequireEmail() : false);
    brunch.setEmailRegexp(
        brunchCreate.getEmailRegexp() != null && brunchCreate.getEmailRegexp().isPresent()
            ? brunchCreate.getEmailRegexp().get()
            : null);

    var builtAuth =
        BrunchAuthorization.builder()
            .brunch(brunch)
            .brunch_id(brunchCreate.getId())
            .adminPasswordHash(
                brunchCreate.getAdminPassword() != null
                    ? brunchCreate.getAdminPassword().orElse(null)
                    : null)
            .votingPasswordHash(
                brunchCreate.getVotingPassword() != null
                    ? brunchCreate.getVotingPassword().orElse(null)
                    : null)
            .build();
    brunch.setBrunchAuthorization(builtAuth);

    List<Question> questions =
        brunchCreate.getQuestions().stream()
            .map(q -> mapToQuestionEntity(q, brunch)) // pass the brunch as parent
            .sorted(
                Comparator.comparing(
                    Question::getOrder, Comparator.nullsLast(Comparator.naturalOrder())))
            .collect(Collectors.toList());

    brunch.setQuestions(questions);

    return brunch;
  }
}
