name: Spotless on PR
on:
  pull_request:
    branches: [ "develop" ]
    types: [ "opened", "synchronize", "reopened" ]

jobs:
  build:
    name: Spotless Apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 24
      - run: mvn install -DskipTests=true -Pspotless
      - run: mvn spotless:apply -Pspotless
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:

          commit_message: "chore(ci): spotless:apply"

          # Optional. Option used by `git-status`to determine if the repository is
          # dirty. See https://git-scm.com/docs/git-status#_options
          status_options: '--untracked-files=no'
